// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package gRPC

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6615c02eDecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGRPC(in *jlexer.Lexer, out *configData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "CorePort":
			out.CorePort = string(in.String())
		case "AuthPort":
			out.AuthPort = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6615c02eEncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGRPC(out *jwriter.Writer, in configData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"CorePort\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.CorePort))
	}
	{
		const prefix string = ",\"AuthPort\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.AuthPort))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v configData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6615c02eEncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGRPC(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v configData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6615c02eEncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGRPC(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *configData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6615c02eDecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGRPC(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *configData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6615c02eDecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGRPC(l, v)
}
