// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package game

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson85f0d656DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame(in *jlexer.Lexer, out *TurnMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "turn":
			out.Turn = string(in.String())
		case "time_remaining_white":
			out.TimeRemainingWhite = int64(in.Int64())
		case "time_remaining_black":
			out.TimeRemainingBlack = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson85f0d656EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame(out *jwriter.Writer, in TurnMessage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"turn\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Turn))
	}
	{
		const prefix string = ",\"time_remaining_white\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.TimeRemainingWhite))
	}
	{
		const prefix string = ",\"time_remaining_black\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.TimeRemainingBlack))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TurnMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson85f0d656EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TurnMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson85f0d656EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TurnMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson85f0d656DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TurnMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson85f0d656DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame(l, v)
}
func easyjson85f0d656DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame1(in *jlexer.Lexer, out *StartMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "color":
			out.Color = string(in.String())
		case "guid":
			out.GUID = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson85f0d656EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame1(out *jwriter.Writer, in StartMessage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"color\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Color))
	}
	{
		const prefix string = ",\"guid\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.GUID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v StartMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson85f0d656EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StartMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson85f0d656EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *StartMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson85f0d656DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StartMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson85f0d656DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame1(l, v)
}
func easyjson85f0d656DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame2(in *jlexer.Lexer, out *RoomParameters) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "duration":
			out.Duration = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson85f0d656EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame2(out *jwriter.Writer, in RoomParameters) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"duration\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Duration))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RoomParameters) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson85f0d656EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RoomParameters) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson85f0d656EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RoomParameters) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson85f0d656DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RoomParameters) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson85f0d656DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame2(l, v)
}
func easyjson85f0d656DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame3(in *jlexer.Lexer, out *ResultMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "result":
			out.Result = string(in.String())
		case "score":
			out.Score = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson85f0d656EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame3(out *jwriter.Writer, in ResultMessage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"result\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Result))
	}
	{
		const prefix string = ",\"score\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Score))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResultMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson85f0d656EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResultMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson85f0d656EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResultMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson85f0d656DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResultMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson85f0d656DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame3(l, v)
}
func easyjson85f0d656DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame4(in *jlexer.Lexer, out *Message) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "MsgType":
			out.MsgType = string(in.String())
		case "Data":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Data).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson85f0d656EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame4(out *jwriter.Writer, in Message) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"MsgType\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.MsgType))
	}
	{
		const prefix string = ",\"Data\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.Data).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Message) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson85f0d656EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Message) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson85f0d656EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Message) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson85f0d656DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Message) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson85f0d656DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame4(l, v)
}
func easyjson85f0d656DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame5(in *jlexer.Lexer, out *InitMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "roomid":
			out.RoomId = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson85f0d656EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame5(out *jwriter.Writer, in InitMessage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"roomid\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.RoomId))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v InitMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson85f0d656EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v InitMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson85f0d656EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *InitMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson85f0d656DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *InitMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson85f0d656DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame5(l, v)
}
func easyjson85f0d656DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame6(in *jlexer.Lexer, out *InfoMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "info":
			out.Info = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson85f0d656EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame6(out *jwriter.Writer, in InfoMessage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"info\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Info))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v InfoMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson85f0d656EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v InfoMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson85f0d656EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *InfoMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson85f0d656DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *InfoMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson85f0d656DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame6(l, v)
}
func easyjson85f0d656DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame7(in *jlexer.Lexer, out *ErrorMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "error":
			out.Error = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson85f0d656EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame7(out *jwriter.Writer, in ErrorMessage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"error\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Error))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ErrorMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson85f0d656EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ErrorMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson85f0d656EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ErrorMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson85f0d656DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ErrorMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson85f0d656DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgGame7(l, v)
}
