// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package user

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson2c1ef15cDecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgUser(in *jlexer.Lexer, out *UserScore) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "email":
			out.Email = string(in.String())
		case "score":
			out.Score = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2c1ef15cEncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgUser(out *jwriter.Writer, in UserScore) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"email\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"score\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Score))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserScore) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2c1ef15cEncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgUser(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserScore) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2c1ef15cEncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgUser(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserScore) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2c1ef15cDecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgUser(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserScore) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2c1ef15cDecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgUser(l, v)
}
