// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  user

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GetScoreParameters ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetScoreParameters ) UnmarshalJSON([]byte) error { return nil }
func ( GetScoreParameters ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetScoreParameters ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetScoreParameters *GetScoreParameters

func ( TestUserDataStruct ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* TestUserDataStruct ) UnmarshalJSON([]byte) error { return nil }
func ( TestUserDataStruct ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* TestUserDataStruct ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_TestUserDataStruct *TestUserDataStruct

func ( User ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* User ) UnmarshalJSON([]byte) error { return nil }
func ( User ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* User ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_User *User

func ( UserScore ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* UserScore ) UnmarshalJSON([]byte) error { return nil }
func ( UserScore ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* UserScore ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_UserScore *UserScore
