// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package controllers

import (
	json "encoding/json"
	user "github.com/go-park-mail-ru/2018_2_parashutnaya_molitva/internal/pkg/user"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson650569b1DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers(in *jlexer.Lexer, out *responseUserGuidStruct) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "user_guid":
			out.UserGuid = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson650569b1EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers(out *jwriter.Writer, in responseUserGuidStruct) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user_guid\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.UserGuid))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v responseUserGuidStruct) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson650569b1EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v responseUserGuidStruct) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson650569b1EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *responseUserGuidStruct) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson650569b1DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *responseUserGuidStruct) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson650569b1DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers(l, v)
}
func easyjson650569b1DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers1(in *jlexer.Lexer, out *responseUploadAvatar) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "avatar":
			out.Avatar = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson650569b1EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers1(out *jwriter.Writer, in responseUploadAvatar) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"avatar\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Avatar))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v responseUploadAvatar) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson650569b1EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v responseUploadAvatar) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson650569b1EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *responseUploadAvatar) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson650569b1DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *responseUploadAvatar) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson650569b1DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers1(l, v)
}
func easyjson650569b1DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers2(in *jlexer.Lexer, out *getUsersCountResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "count":
			out.Count = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson650569b1EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers2(out *jwriter.Writer, in getUsersCountResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"count\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Count))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v getUsersCountResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson650569b1EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v getUsersCountResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson650569b1EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *getUsersCountResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson650569b1DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *getUsersCountResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson650569b1DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers2(l, v)
}
func easyjson650569b1DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers3(in *jlexer.Lexer, out *SignInParameters) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "email":
			out.Email = string(in.String())
		case "password":
			out.Password = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson650569b1EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers3(out *jwriter.Writer, in SignInParameters) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"email\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"password\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Password))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SignInParameters) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson650569b1EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SignInParameters) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson650569b1EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SignInParameters) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson650569b1DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SignInParameters) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson650569b1DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers3(l, v)
}
func easyjson650569b1DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers4(in *jlexer.Lexer, out *GetUsersScoreResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "scores":
			if in.IsNull() {
				in.Skip()
				out.Scores = nil
			} else {
				in.Delim('[')
				if out.Scores == nil {
					if !in.IsDelim(']') {
						out.Scores = make([]user.UserScore, 0, 2)
					} else {
						out.Scores = []user.UserScore{}
					}
				} else {
					out.Scores = (out.Scores)[:0]
				}
				for !in.IsDelim(']') {
					var v1 user.UserScore
					(v1).UnmarshalEasyJSON(in)
					out.Scores = append(out.Scores, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson650569b1EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers4(out *jwriter.Writer, in GetUsersScoreResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"scores\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.Scores == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Scores {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetUsersScoreResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson650569b1EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetUsersScoreResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson650569b1EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetUsersScoreResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson650569b1DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetUsersScoreResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson650569b1DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers4(l, v)
}
func easyjson650569b1DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers5(in *jlexer.Lexer, out *FindUserResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "roomid":
			out.RoomID = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson650569b1EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers5(out *jwriter.Writer, in FindUserResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"roomid\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.RoomID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FindUserResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson650569b1EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FindUserResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson650569b1EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FindUserResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson650569b1DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FindUserResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson650569b1DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers5(l, v)
}
func easyjson650569b1DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers6(in *jlexer.Lexer, out *ErrorResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "error":
			out.Error = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson650569b1EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers6(out *jwriter.Writer, in ErrorResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"error\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Error))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ErrorResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson650569b1EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ErrorResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson650569b1EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ErrorResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson650569b1DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ErrorResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson650569b1DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers6(l, v)
}
func easyjson650569b1DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers7(in *jlexer.Lexer, out *ErrorFormResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "error":
			out.Error = string(in.String())
		case "field":
			out.Field = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson650569b1EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers7(out *jwriter.Writer, in ErrorFormResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"error\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Error))
	}
	{
		const prefix string = ",\"field\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Field))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ErrorFormResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson650569b1EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ErrorFormResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson650569b1EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ErrorFormResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson650569b1DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ErrorFormResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson650569b1DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers7(l, v)
}
func easyjson650569b1DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers8(in *jlexer.Lexer, out *CreateUserParameters) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "email":
			out.Email = string(in.String())
		case "password":
			out.Password = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson650569b1EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers8(out *jwriter.Writer, in CreateUserParameters) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"email\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"password\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Password))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateUserParameters) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson650569b1EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateUserParameters) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson650569b1EncodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateUserParameters) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson650569b1DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateUserParameters) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson650569b1DecodeGithubComGoParkMailRu20182ParashutnayaMolitvaInternalPkgControllers8(l, v)
}
